### ISSUE TITLE
Question about online baseline prediction in MIXER

### ISSUE THREAD

**Issue by lifelongeek** [facebookresearch/MIXER#5]
This issue may be seen as extension of https://github.com/facebookresearch/MIXER/issues/4.
However, I am making new issue to ask more specific question.

I understand that average reward term (\bar(r)_{t}_) comes from 'online baseline prediction' method introduced in Reinforcement Learning Neural Turing Machine (RL-NTM) Paper. Specifically, this term seems coming from E_p_theta(a_{t:T}_|a_{1:(t-1)}_)R(a_{t:T}).

Let me ask some questions related to \bar(r)_{t} .  I am grateful for your time and effort to read these questions.

Question1) Why \bar(r)_{t}_ is called as 'average reward'? Can you clarify whether \bar(r)_{t} = b_t (=baseline prediction for time t) or not?

Question2) How can we sure that LSTM RNN can estimate E_p_theta(a_{t:T}|a_{1:(t-1)})r(a_{1:T}) by linear regression? Does h_t contain enough information to estimate this term? Especially in earlier time step,it may be hard for network to predict future reward.

Question3) Why affine transformation for linear regression is initialized as Weight = 0, bias = 0.01 ?

Thank you !

**Comment by ranzato** [comment]
Sorry for the delay. 

1) Yes, my \bar{r}_t is denoted as b_t in their paper. I called it average reward because I think of it as the average (cumulative) reward we expect given the current input and hidden state. It is the baseline the model has to beat in order to reinforce the sequence of words it has chosen. Again, this is just one way to interpret the learning rule. I just understand it better by thinking in the actor-critique framework (actor=model, critique=baseline the model is trying to beat), as opposed to a mere mathematical derivation for variance reduction.

2) I cannot guarantee it but in practice it works. Remember that we do curriculum training, and therefore, the hidden state is pretty informative to start with.

3) other initializations may work too and it does not need to be like that. I just thought to start by predicting a small constant reward (hopefully matching the average reward the model gets at that point), and let the model later make use also of the matrix W. Again, I do not think these initialization are particularly crucial.

**Comment by SeekPoint** [comment]
so, in the code,
"cum_reward_predictors "is the  linear regressor to estimate the average reward term (\bar(r){t}) (namely E_p_theta(a_{t:T}|a_{1:(t-1)})r(a_{1:T})) 

am I right on this?
